= SSI sagt Good By PDF  
:author: Berthold Maier
:revnumber: v0.1
:revdate: 04.03.2020
:revremark: Draft / Unveröffentlicht
:sectnums:         
:toc:          
:toclevels: 4                                          
:toc-title: Die Zukunft der Digitalisierung ohne PDF 
:description: Der Weg mit SSI von dokumentzentrischen den Prozessen Prozessen mti PDF hin zu medienbruchfreien rechstsicher Verträgen      
:keywords: DID, VerifiableCredential, VC, ADC, ACDC, KERI
:imagesdir: ./images


== Motivation
Es ist Zeit darüber zu sprechen wie uns das PDF Format beim Wandel zur digitalen Welt hemmt.
Hier sind einige Gründe warum wir das PDF Format hinter uns lassen sollten.

Verträge: 
Immer mehr Unternehmen breiten ihr Geschäftsmodell auf den Onlinehandel und rein digitale Kommunikation aus. Die schnelle,effizieten, sichere und medienbruchfreie digitale Verarbeitung ist hier ein wichtiges Kriterium.
Wie bei jendem Gschäft kommt es auch beim Online-Handel zu Verträgen und diese müssen spätestens bei einer Auseindersetzung eine rechtssichere Form aufweisen - die EU eIDAS Grundverordnung regelt dies. Die Lösung mit Unterschrift auf einem Dokument, Scan und Ablage in einem DMS ist möglich, aber sehr unständlich und auch nur bedingt rechtsicher. Die oft gewählte Lösung der digitalen Signatur (X.509 Zertifikat) in Verbindung mit einem PDF Dokument stellt eine Möglichkeit der  fortgeschrittenen oder quaifizierten Signatur dar und klingt zuerst einmal vielversprechend. Der Verlust der strukturierten Informationen im PDF Format schränkt jedoch eine spätere  automatisierte Verbreitung enorm ein und ist deshalb in der  modernen digitalisierten Welt nur eine theoretisch Option.   


Liegt ein PDF Dokument einmal vor, Es muss also in eine strukturierte Form umgewandelt werden, was Fehlerfrei fast nur manuell möglich ist - auch KI-Methoden sind nur eine Reporduktion und können nicht zu 100% die Richtigkeit belegen. 
Gefordert ist aber eine medienbruchfrei Kommunikation, die zeitgleich rechtssicher ist. Hier scheidet also PDF aus. 

Behördenanträge:
Das Online-Zusgansgesetzt (OZG) fordert einen digitalen und medeinbruchfreien Austausch 



